# Generated by Django 4.1.7 on 2023-02-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Eg. 2021-09-28T19:40:02.785988+05:45', verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Eg. 2021-09-28T19:40:02.785988+05:45', verbose_name='Updated Date')),
                ('product_name', models.CharField(max_length=500)),
                ('sku', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('uploaded_file', models.FileField(null=True, upload_to='file_upload/file/%Y/%m/%d/')),
                ('video_image', models.ImageField(upload_to='images/product_image')),
                ('sizes', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
